site_name: RickDb
site_description: Simple SQL database layer
strict: true
site_url: https://git.oddbit.org/OddBit/rick_db
repo_name: OddBit/rick_db
repo_url: https://git.oddbit.org/OddBit/rick_db

theme:
  name: material
  palette:
  - scheme: slate
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: default
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  language: en

nav:
- Overview: index.md
- install.md
- connection.md
- object_mapper.md
- Query Builder: building_queries.md
- repository.md
- grid.md
- migrations.md
- Class List:
  - Record: 'classes/record.md'
  - Connection: 'classes/connection.md'
  - Cursor: 'classes/cursor.md'
  - Profiler: 'classes/profiler.md'
  - Repository: 'classes/repository.md'
  - SqlDialect: 'classes/sqldialect.md'
  - Select: 'classes/select.md'
  - Insert: 'classes/insert.md'
  - Update: 'classes/update.md'
  - Delete: 'classes/delete.md'
  - Literal: 'classes/literal.md'
  - CTEs (With): 'classes/with.md'
  - DbGrid: 'classes/dbgrid.md'
  - QueryCache: 'classes/querycache.md'
  - Pool: 'classes/poolinterface.md'
  - Manager:
    - Manager: 'classes/managerinterface.md'
    - PgManager: 'classes/pgmanager.md'
    - Sqlite3Manager: 'classes/sqlite3manager.md'

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- mdx_include

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/oddbit-project/rick_db
