[tox]
envlist =flake, py310, py311, py312, py313, py314

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/rick_db
commands =
    coverage erase
    coverage run -m pytest --cov=rick_db --cov-append --cov-report=term-missing
deps = -rrequirements-dev.txt

[testenv:flake]
commands = flake8 rick_db/ tests/ setup.py

[flake8]
exclude =
    .tox,
    .git,
    .env,
    dist,
    build
ignore = E501, W504 ,F401, F403, W503, E203, E261, E201
max_line_length = 127

[docker:pg_db]
image=postgres:12-alpine
environment =
    POSTGRES_USER=some_user
    POSTGRES_PASSWORD=somePassword
    POSTGRES_DB=testdb

expose =
    PGPORT=5432/tcp

healthcheck_cmd = psql \
    --user=$POSTGRES_USER --dbname=$POSTGRES_DB \
    --quiet --no-align --tuples-only -1 --command="SELECT 1"

healthcheck_timeout = 1
healthcheck_retries = 30
healthcheck_interval = 1
healthcheck_start_period = 1
host_var = PGHOST

[docker:clickhouse_db]
image=clickhouse/clickhouse-server:25.8
environment =
    CLICKHOUSE_USER=some_user
    CLICKHOUSE_PASSWORD=somePassword
    CLICKHOUSE_DB=testdb
    CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

expose =
    CLICKHOUSE_PORT=8123/tcp

healthcheck_cmd = wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
healthcheck_timeout = 1
healthcheck_retries = 30
healthcheck_interval = 1
healthcheck_start_period = 5
host_var = CLICKHOUSE_HOST


[testenv:py{310,311,312,313,314}]
docker =
    pg_db
    clickhouse_db

setenv =
    POSTGRES_USER=some_user
    POSTGRES_PASSWORD=somePassword
    POSTGRES_DB=testdb
    CLICKHOUSE_USER=some_user
    CLICKHOUSE_PASSWORD=somePassword
    CLICKHOUSE_DB=testdb


