[tox]
envlist =flake, py310, py311, py312, py313, py314

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/rick_db
commands =
    coverage erase
    coverage run -m pytest --cov=rick_db --cov-append --cov-report=term-missing
deps = -rrequirements-dev.txt

[testenv:flake]
commands = flake8 rick_db/ tests/ setup.py

[flake8]
exclude =
    .tox,
    .git,
    .env,
    dist,
    build
ignore = E501, W504 ,F401, F403, W503, E203, E261, E201
max_line_length = 127
